group: stable
os: linux
sudo: false

language: node_js
node_js:
  - 8

script:
  - yarn test

after_success:
  - yarn build
  - test $TRAVIS_BRANCH = "master" && surge --project ./build --domain $SURGE_DOMAIN

cache:
  yarn: true
  directories:
    - node_modules
