# Setup SURGE_DOMAIN, SURGE_TOKEN and SURGE_EMAIL environment variables for auto deploy to work
group: stable
os: linux
sudo: false

language: node_js
node_js:
  - 8

script:
  - yarn test

after_success:
  - test $TRAVIS_BRANCH = "master" && yarn build:production
  - test $TRAVIS_BRANCH = "master" && surge --project ./build --domain $SURGE_DOMAIN

cache:
  yarn: true
  directories:
    - node_modules
